[package]
name = "pgso-signal-egemaps"
version = "0.1.0"
edition = "2021"

[features]
default = ["egemaps"]
egemaps = []

[dependencies]
pgso-core = { path = "../pgso-core" }

[dev-dependencies]
criterion = { version = "0.5", features = ["html_reports"] }

[[bench]]
name = "latency"
harness = false
